### ISSUE TITLE
crashes without description

### ISSUE THREAD

**Issue by xorus** [xorus/XorusCalendarBot#1]
DSharpPlus.SlashCommands.SlashCommandsExtension, System.NullReferenceException: Object reference not set to an instance of an object.
ffxiv-calendar-1  |    at XorusCalendarBot.SlashCommands.ReplaceThings(String str, Dictionary`2 placeholders, Boolean escape) in /src/XorusCalendarBot/SlashCommands.cs:line 23
ffxiv-calendar-1  |    at XorusCalendarBot.SlashCommands.FormatEvent(String nextDateMessage, Occurrence next, Boolean allowDescription) in /src/XorusCalendarBot/SlashCommands.cs:line 44
ffxiv-calendar-1  |    at XorusCalendarBot.SlashCommands.<>c__DisplayClass6_0.<NextEvent>b__1(String current, Occurrence occurrence) in /src/XorusCalendarBot/SlashCommands.cs:line 80
ffxiv-calendar-1  |    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)

**Comment by xorus** [comment]
```
ffxiv-calendar-1  | Error: DSharpPlus.SlashCommands.SlashCommandsExtension, System.NullReferenceException: Object reference not set to an instance of an object.
ffxiv-calendar-1  |    at XorusCalendarBot.Discord.SlashCommands.ReplaceThings(String str, Dictionary`2 placeholders, Boolean escape) in /src/XorusCalendarBot/Discord/SlashCommands.cs:line 22
ffxiv-calendar-1  |    at XorusCalendarBot.Discord.SlashCommands.FormatEvent(String nextDateMessage, Occurrence next, Boolean allowDescription) in /src/XorusCalendarBot/Discord/SlashCommands.cs:line 43
ffxiv-calendar-1  |    at XorusCalendarBot.Discord.SlashCommands.<>c__DisplayClass6_0.<NextEvent>b__1(String current, Occurrence occurrence) in /src/XorusCalendarBot/Discord/SlashCommands.cs:line 81
ffxiv-calendar-1  |    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
ffxiv-calendar-1  |    at XorusCalendarBot.Discord.SlashCommands.NextEvent(InteractionContext ctx, Nullable`1 count) in /src/XorusCalendarBot/Discord/SlashCommands.cs:line 77
ffxiv-calendar-1  |    at DSharpPlus.SlashCommands.SlashCommandsExtension.RunCommand(BaseContext context, MethodInfo method, IEnumerable`1 args)
ffxiv-calendar-1  |    at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass45_0.<<InteractionHandler>b__0>d.MoveNext()
```
